apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: iot-home-sk
  labels:
    name: WISE-PaaS
  annotations:
    kubernetes.io/ingress.class: nginx
    # nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  rules:
    - host: iot-home-sk.assignment.eks004.en.internal
      http:
        paths:
          - path: /?(.*)
            pathType: Prefix
            backend:
              service:
                name: server-sk
                port:
                  number: 3000
