apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: iot-home-dave-lee
  annotations:
    kubernetes.io/ingress.class: nginx
    # nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  rules:
  # SA DataCenter
    - host: iot-home-dave-lee.assignment.eks004.en.internal
  # HZ DataCenter
    # - host: iot-home-dave-lee.assignment.eks006.en.internal
      http:
        paths:
          - path: /
            backend:
              serviceName: server-dave-lee
              servicePort: 3000
