apiVersion: v1
kind: Service
{{- with .Values.svcClusterIps.server }}
metadata:
  name: {{ .name }}
spec:
  type: ClusterIP
  selector:
    {{- range .selectors }}
    {{ .selectorKey }}: {{ .selectorValue }}
    {{- end }}
  ports:
    {{- range .ports  }}
    - port: {{ .port }}
      targetPort: {{ .targetPort }}
    {{- end  }}
{{- end }}