apiVersion: apps/v1
kind: Deployment
{{- with .Values.deployParams.iothubMqtt }}
metadata:
  name: {{ .name }}
spec:
  replicas: {{ .replicaCount }}
  selector:
    matchLabels:
      {{ .labelKey }}: {{ .labelValue }}
  template:
    metadata:
      labels:
        {{ .labelKey }}: {{ .labelValue }}
{{- end }}
    spec:
      containers:
        - name: mqtt
          {{- with .Values.containerParams.mqtt}}
          image: {{ printf "%s/%s:%s" .repository .imageName .version }}
          {{- if .resources }}
          resources:
            limits:
              cpu: {{ .resources.limits.cpu }}
              memory: {{ .resources.limits.memory }}
              ephemeral-storage: {{ .resources.limits.ephemeralStorage }}
            requests:
              cpu: {{ .resources.requests.cpu }}
              memory: {{ .resources.requests.memory }}
          {{- end }}
          {{- end }}
          env:
            - name: ENSAAS_SERVICES
              valueFrom:
                secretKeyRef:
                  name: {{ include "iot-home-helm.secret" . }}
                  key: ENSAAS_SERVICES