apiVersion: apps/v1
kind: Deployment
{{- with .Values.deployParams.server }}
metadata:
  name: {{ .name }}
spec:
  replicas: {{ .replicaCount }}
  selector:
    matchLabels:
      {{- range .labels }}
      {{ .labelKey }}: {{ .labelValue }}
      {{- end }}
  template:
    metadata:
      labels:
        {{- range .labels }}
        {{ .labelKey }}: {{ .labelValue }}
        {{- end }}
{{- end }}
    spec:
      containers:
        - name: server
          {{- with .Values.containerParams.server}}
          image: {{ printf "%s/%s:%s" .repository .imageName .tag }}
          imagePullPolicy: Always
          ports:
            - containerPort: {{ .port }}
          {{- if .resources }}
          resources:
            limits:
              cpu: {{ .resources.limits.cpu }}
              memory: {{ .resources.limits.memory }}
              ephemeral-storage: {{ .resources.limits.ephemeralStorage }}
            requests:
              cpu: {{ .resources.requests.cpu }}
              memory: {{ .resources.requests.memory }}
          {{- end }}
          {{- end }}
          env:
            - name: ENSAAS_SERVICES
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.global.database.secretName }}
                  key: ENSAAS_SERVICES