apiVersion: v1
kind: Service
{{- with .Values.svcClusterIps.server }}
metadata:
  name: {{ .name }}-cluster-ip-service
spec:
  type: ClusterIP
  selector:
    {{ .selectorKey }}: {{ .selectorValue }}
  ports:
    {{- range .ports  }}
    - port: {{ .port }}
      targetPort: {{ .targetPort }}
    {{- end  }}
{{- end }}